name: NemoriaQuest
description: >
  Modular quest engine for Paper 1.21.x. Create story-driven quests using YAML models
  with branches, conditions, Citizens NPCs, GUI menus, scoreboard tracking and full
  multilingual support (Polish/English).
main: net.nemoria.quest.NemoriaQuestPlugin
version: ${project.version}
api-version: 1.21
author: Nemoria / MaciekJRPL
softdepend:
  - PacketEvents
  - Vault
  - Citizens
  - MythicMobs
  - PlaceholderAPI
commands:
  nemoriaquest:
    aliases: [nq]
    description: Main command for NemoriaQuest
permissions:
  nemoriaquest.command:
    default: op
  nemoriaquest.command.reload:
    default: op
  nemoriaquest.command.start:
    default: op
  nemoriaquest.command.stop:
    default: op
  nemoriaquest.command.active:
    default: true
  nemoriaquest.command.list:
    default: true
  nemoriaquest.command.info:
    default: true
  nemoriaquest.command.complete:
    default: op
  nemoriaquest.command.progress:
    default: op
  nemoriaquest.command.debug:
    default: op
  nemoriaquest.command.gui:
    default: true
